
# email and level are required for users
#
users:
  - email: <%= ENV.fetch("ADMIN_EMAIL", "admin@barong.io") %>
    password: <%= ENV.fetch("ADMIN_PASSWORD", nil) %>
    role: "admin"
    state: "active"
    level: 4

levels:
  - requirements:
      email: "verified"
    description: "User clicked on the confirmation link"
  - requirements:
      phone: "verified"
    description: "User entered a valid code from sms"
  - requirements:
      profile: "verified"
    description: "User submitted his personal information"
  - requirements:
      document: "verified"
    description: "User personal documents have been verified"
